sudo: required
services:
  - docker
script:
  - docker build -t mozamimy/cerebro .
env:
  REPOSITORY: mozamimy/cerebro
after_success:
  - if [ "$TRAVIS_TAG" != "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
    docker tag $REPOSITORY $REPOSITORY:`cat VERSION` &&
    docker push $REPOSITORY:`cat VERSION` &&
    docker tag $REPOSITORY $REPOSITORY:latest &&
    docker push mozamimy/cerebro:latest ;
    fi
notifications:
  on_success: always
  on_failure: always
  on_start: false
